[tool.briefcase]
project_name = "Idea Eater"
bundle = "com.example"
version = "0.0.1"
url = "https://github.com/mattcen/idea_eater"
license.file = "LICENSE"
author = 'Matt Cengia, Lilly Ryan'
author_email = "mattcen@mattcen.com, lilly@attacus.net"

[tool.briefcase.app.idea_eater]
formal_name = "Idea Eater"
description = "Takes ideas and eats them"
icon = "src/idea_eater/resources/idea_eater"
sources = ['src/idea_eater']
requires = []


[tool.briefcase.app.idea_eater.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.idea_eater.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.idea_eater.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.idea_eater.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.idea_eater.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
